version: '2'
services:
  nginx:
    image: 'nginx:latest'
    ports:
      - 5043:443
    links:
      - registry:registry
    volumes:
      - ./nginx/:/etc/nginx/conf.d
  registry:
    image: registry:2
    ports:
      - '5000:5000'
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - '80:80'
    environment:
      REGISTRY_URL: 'http://127.0.0.1:5000'
